repos:
  - repo: https://github.com/commitizen-tools/commitizen
    rev: "8519ca470e88f8c7eb30dfe31cad2b0dd8acfea2"  # frozen: v4.2.1
    hooks:
      - id: commitizen
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "cef0300fd0fc4d2a87a85fa2093c6b283ea36f4b"  # frozen: v5.0.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/psf/black
    rev: "25.1.0"  # frozen: 25.1.0
    hooks:
      - id: black
  - repo: https://github.com/pycqa/isort
    rev: "0a0b7a830386ba6a31c2ec8316849ae4d1b8240d"  # frozen: 6.0.0
    hooks:
      - id: isort
  - repo: https://github.com/andreoliwa/nitpick
    rev: "36d4912df1f0bd2ed8cc535b57c5ba3b09ce3d46" # frozen: v0.35.0
    hooks:
      - id: nitpick
  - repo: "https://github.com/TotallyNotRobots/check-spdx-header"
    rev: 'c5b3cb2f735d44f46ad132426fca49f418d73ba6'  # frozen: 0.1.0a3
    hooks:
      - id: fix-spdx-header
  - repo: https://github.com/ikamensh/flynt
    rev: "651c822fdcf45fffcf9743dc755085f32acb65e3" # frozen: 1.0.1
    hooks:
      - id: flynt
  - repo: https://github.com/codespell-project/codespell
    rev: '63c8f8312b7559622c0d82815639671ae42132ac'  # frozen: v2.4.1
    hooks:
      - additional_dependencies:
          - tomli ; python_version < '3.11'
        id: codespell
  - repo: https://github.com/asottile/pyupgrade
    rev: 'ce40a160603ab0e7d9c627ae33d7ef3906e2d2b2'  # frozen: v3.19.1
    hooks:
      - id: pyupgrade
        args:
          - --py38-plus
minimum_pre_commit_version: 2.18.0
default_install_hook_types:
  - pre-commit
  - pre-push
  - commit-msg
